// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mwjnevxctlxpunqpjmtd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13am5ldnhjdGx4cHVucXBqbXRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMzk5MjYsImV4cCI6MjA2NzgxNTkyNn0.FNh6XWtgG7h23fV0MebJtnF0ZVyCA8w5bReHxNtTiyE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});